<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'id' => 1,
                'title' => 'Home Page',
                'meta_title' => 'Real Estate Investments Solutions | Saras',
                'meta_keywords' => 'real estate, saras, commercial investment, residential properties, luxury properties, real estate investment,',
                'meta_description' => 'Saras is one of the best real estate company in Delhi. Best investment solutions in commercial, residential, and luxury properties.',
                'short_description' => '<h1 class="h1">Invest In Your Dream Project</h1><p class="mt-4">We Have The Best Investment Properties For You.</p>',
                'description' => NULL,
                'image' => '1715535026.png',
                'status' => '1',
                'created_at' => '2024-02-05 16:49:09',
                'updated_at' => '2025-12-09 04:32:59',
                'scripts' => NULL,
            ],
            [
                'id' => 2,
                'title' => 'About us',
                'meta_title' => 'About us | Sri Ganganagar  Milk Union',
                'meta_keywords' => 'About us | Sri Ganganagar  Milk Union',
                'meta_description' => 'About us | Sri Ganganagar  Milk Union',
                'short_description' => '<p style="text-align: justify;">Sriganganagar Milk Union was established in March, 1981 with average milk procurement of 300 ltrs/per day, Sriganganagar Milk Union was registered under rajasthan co-operative act 1965 with the motto to pay remunerative price to its milk producers around the year at their door step alongwith technical input services such as animal health care, supply of balance cattle feed, supplements and breed improvement programmes through Artificial Insemination and Natural Services and to provide quality products to consumer at competitive price.</p>',
                'description' => '<div class="section-inner-header about-inner-header"><h6>&nbsp;</h6><h6>About Our Company</h6><h2>We Are Always Ensure Best Medical Treatment For Your Health</h2></div><p>Sriganganagar Milk Union was established in March, 1981 with average milk procurement of 300 ltrs/per day, Sriganganagar Milk Union was registered under rajasthan co-operative act 1965 with the motto to pay remunerative price to its milk producers around the year at their door step alongwith technical input services such as animal health care, supply of balance cattle feed, supplements and breed improvement programmes through Artificial Insemination and Natural Services and to provide quality products to consumer at competitive price.</p><p>It has a own Dairy plant handling capacity 1.0 lakh ltrs. per day with the facilities to pack milk, ghee etc., Its main products are Ghee, Liquid Milk, Paneer, Chhach, Lassi and Dahi. Milk Union is having four own Milk Chilling Plant at Nohar, Suratgarh, Gharsana and Padampur and two out-sourced Chilling Plants at Bhadra and Pallu.</p><p>Sriganganagar Milk Union is an ISO 22000:2018 &amp; IS 15000 (HACCP) certified organisation. This Milk Union is affiliated to Rajasthan Co-perative Dairy Federation Ltd., Jaipur.</p><p>Sriganganagar Milk Union was established in March, 1981 with average milk procurement of 300 ltrs/per day, Sriganganagar Milk Union was registered under rajasthan co-operative act 1965 with the motto to pay remunerative price to its milk producers around the year at their door step alongwith technical input services such as animal health care, supply of balance cattle feed, supplements and breed improvement programmes through Artificial Insemination and Natural Services and to provide quality products to consumer at competitive price.</p><p>It has a own Dairy plant handling capacity 1.0 lakh ltrs. per day with the facilities to pack milk, ghee etc., Its main products are Ghee, Liquid Milk, Paneer, Chhach, Lassi and Dahi. Milk Union is having four own Milk Chilling Plant at Nohar, Suratgarh, Gharsana and Padampur and two out-sourced Chilling Plants at Bhadra and Pallu.</p><p>Sriganganagar Milk Union is an ISO 22000:2018 &amp; IS 15000 (HACCP) certified organisation. This Milk Union is affiliated to Rajasthan Co-perative Dairy Federation Ltd., Jaipur.</p>',
                'image' => '1763397391.jpg',
                'status' => '1',
                'created_at' => '2024-02-05 17:22:06',
                'updated_at' => '2025-12-09 04:32:27',
                'scripts' => NULL,
            ],
            [
                'id' => 3,
                'title' => 'Contact Us',
                'meta_title' => 'Contact Us - Saras',
                'meta_keywords' => 'contact us, get in touch, inquiries, collaboration, assistance, support',
                'meta_description' => "Connect with Saras's dedicated team. Whether you have inquiries, seek collaboration opportunities, or need assistance, our contact page is your gateway to seamless communication. Reach out today and let's engage in meaningful conversations.",
                'short_description' => "<h2>Let's Send Us a Message Below</h2>",
                'description' => '<p>Contact Info</p><h2>Let\'s Connect With Us</h2><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam imperdiet varius mi, ut hendrerit magna mollis ac.</p>',
                'image' => '1707155696.jpg',
                'status' => '1',
                'created_at' => '2024-02-05 17:54:56',
                'updated_at' => '2025-11-24 18:08:35',
                'scripts' => NULL,
            ],
            [
                'id' => 4,
                'title' => 'Media & Press',
                'meta_title' => 'Media & Press',
                'meta_keywords' => 'Media & Press',
                'meta_description' => 'Media & Press',
                'short_description' => '<h2 class="breadcrumb-title">Media &amp; Press</h2>',
                'description' => '<h2 class="breadcrumb-title">Media &amp; Press</h2>',
                'image' => '1707760058.jpg',
                'status' => '1',
                'created_at' => '2024-02-12 17:47:38',
                'updated_at' => '2025-12-03 03:13:50',
                'scripts' => 'Media & Press',
            ],
            [
                'id' => 5,
                'title' => 'Error 404',
                'meta_title' => 'Error 404',
                'meta_keywords' => 'Error 404',
                'meta_description' => 'Error 404',
                'short_description' => '<p>Error 404</p>',
                'description' => '<h1 class="title">Page not found!</h1><p>Sorry, but the page you were looking for could not be found.</p>',
                'image' => '1708854786.jpg',
                'status' => '1',
                'created_at' => '2024-02-25 09:53:06',
                'updated_at' => '2024-02-25 10:44:45',
                'scripts' => NULL,
            ],
            [
                'id' => 7,
                'title' => 'Service',
                'meta_title' => 'Service',
                'meta_keywords' => 'Service',
                'meta_description' => 'Service',
                'short_description' => '<p>Service</p>',
                'description' => '<h2>We Provide a Wide Variety of It Services</h2>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2024-04-03 18:49:02',
                'updated_at' => '2024-04-04 18:54:17',
                'scripts' => NULL,
            ],
            [
                'id' => 8,
                'title' => 'Blog',
                'meta_title' => 'Blog',
                'meta_keywords' => 'Blog',
                'meta_description' => 'Blog',
                'short_description' => '<p>Blog</p>',
                'description' => '<p>Blog</p>',
                'image' => '1714822393.jpg',
                'status' => '1',
                'created_at' => '2024-04-04 18:30:31',
                'updated_at' => '2024-05-04 11:33:13',
                'scripts' => NULL,
            ],
            [
                'id' => 9,
                'title' => 'Board of directors',
                'meta_title' => 'Board of directors',
                'meta_keywords' => 'Board of directors',
                'meta_description' => 'Board of directors',
                'short_description' => "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>",
                'description' => "<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>",
                'image' => '1714564056.jpg',
                'status' => '1',
                'created_at' => '2024-04-08 17:51:33',
                'updated_at' => '2025-10-20 11:53:14',
                'scripts' => NULL,
            ],
            [
                'id' => 10,
                'title' => 'Ready to Go',
                'meta_title' => 'Ready to Go',
                'meta_keywords' => 'Ready to Go',
                'meta_description' => 'Ready to Go',
                'short_description' => '<p>Comming Soon...</p>',
                'description' => '<p>Welcome to "Saras", where we believe in empowering individuals and businesses with cutting-edge digital solutions tailored to their needs. Our mission is simple: to make technology accessible and customizable for everyone, regardless of their technical expertise.</p><p>At "Saras", we understand that not everyone has the resources or expertise to build custom web applications from scratch. That\'s why we offer a range of pre-built web applications that cater to various industries and use cases. Whether you\'re a small business looking to establish your online presence or a nonprofit organization seeking to streamline your operations, we have the perfect solution.</p><p>Our pre-built web applications are designed to be user-friendly and intuitive, allowing you to get up and running quickly without any technical hassle. From e-commerce platforms to content management systems, we have diverse solutions to meet your specific requirements.</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2024-04-08 18:34:50',
                'updated_at' => '2024-04-08 18:44:24',
                'scripts' => NULL,
            ],
            [
                'id' => 11,
                'title' => 'Privacy Policy',
                'meta_title' => 'Privacy Policy',
                'meta_keywords' => 'Privacy Policy',
                'meta_description' => 'Privacy Policy',
                'short_description' => NULL,
                'description' => '<p>Saras is committed to protecting the privacy and security of your personal information. This Privacy Policy describes how we collect, use, and disclose personal information when you visit our website or use our services.</p><p><strong>Information We Collect:</strong></p><p><strong>We may collect personal information that you provide to us when you:</strong></p><ul><li>Register for an account</li><li>Use our services</li><li>Contact us for support or inquiries</li><li>Subscribe to our newsletter or marketing communications</li><li>Participate in surveys or promotions</li></ul><p><strong>The types of personal information we may collect include:</strong></p><ul><li>Name</li><li>Contact information (email address, phone number, mailing address)</li><li>Property preferences and search criteria</li><li>Demographic information</li><li>Payment information (if applicable)</li><li>Communications preferences</li></ul><p><strong>How We Use Your Information</strong></p><p><strong>We may use your personal information for the following purposes:</strong></p><ul><li>To provide and improve our services</li><li>To personalize your experience and tailor our offerings to your preferences</li><li>To communicate with you, including responding to inquiries and providing customer support</li><li>To send you marketing communications, newsletters, and promotional offers</li><li>To conduct research and analysis to better understand our users needs and improve our services</li><li>To comply with legal obligations and enforce our terms of service</li></ul><p><strong>Data Security</strong></p><p>We implement security measures to protect your personal information from unauthorized access, disclosure, alteration, or destruction. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.</p><p><strong>Sharing of Information</strong></p><p><strong>We may share your personal information with third parties for the following purposes:</strong></p><p><strong>Service providers:</strong> We may share your information with third-party service providers who help us provide and improve our services, such as hosting providers, analytics providers, and payment processors.</p><p><br /><strong>Business partners: </strong>We may share information with trusted business partners who offer products or services that may be interest to you.</p><p><br /><strong>Legal purposes:</strong> We may disclose information when required by law, court order, or other legal process, or to protect our rights or the rights of others.</p><p><strong>Your Choices</strong></p><p><strong>You have the following choices regarding your personal information:</strong></p><p>You can update or correct your information by accessing your account settings.<br />You can opt out of receiving marketing communications by following the unsubscribe instructions included in the communication. You can request to delete your account and personal information, subject to certain exceptions where we are required to retain information by law or for legitimate business purposes.</p><p><strong>Changes to This Privacy Policy</strong></p><p>We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of any material changes by posting the updated policy on our website and updating the "last updated" date.</p><p><strong>Contact Us</strong></p><p>If you have any questions or concerns about this Privacy Policy or our practices regarding your personal information, please contact us at <strong>contact@saras.com</strong></p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2024-05-29 14:59:03',
                'updated_at' => '2024-05-29 14:59:03',
                'scripts' => NULL,
            ],
            [
                'id' => 12,
                'title' => 'Terms and Conditions',
                'meta_title' => 'Terms and Conditions',
                'meta_keywords' => 'Terms and Conditions',
                'meta_description' => 'Terms and Conditions',
                'short_description' => NULL,
                'description' => '<p>These Terms and Conditions ("Terms") govern your use of <strong>Saras website ("<strong>www.saras.com</strong>") and any services provided therein. By accessing or using the Website, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use the Website.</p><p><strong>Use of the Website:</strong></p><p><strong>Eligibility:</strong> You must be at least 18 years old to use the Website. By using the Website, you represent and warrant that you are of legal age to form a binding contract with Saras.</p><p><strong>Accuracy of Information:</strong> You agree to provide accurate and complete information when using the Website, including when registering for an account or submitting inquiries.</p><p><strong>Prohibited Activities:</strong> You agree not to engage in any of the following activities:</p><ul><li>Violating any laws or regulations</li><li>Using the Website in any manner that could interfere with, disrupt, or negatively affect other users\' experience</li><li>Attempting to gain unauthorized access to any part of the Website or its systems</li><li>Transmitting any viruses, malware, or other harmful code</li></ul><p><strong>Intellectual Property:</strong></p><p><strong>Ownership:</strong> The Website and its content, including but not limited to text, graphics, logos, and images, are owned by <strong>Saras</strong> or its licensors and are protected by copyright and other intellectual property laws.</p><p><strong>License:</strong> Saras grants you a limited, non-exclusive, non-transferable license to access and use the Website for personal, non-commercial purposes.</p><p><strong>Restrictions:</strong> You agree not to reproduce, modify, distribute, or create derivative works based on the Website or its content without the prior written consent of Saras.</p><p><strong>Privacy:</strong></p><p>By using the Website, you consent to the collection, use, and disclosure of your personal information as described in our Privacy Policy.</p><p><strong>Disclaimer of Warranties:</strong></p><p><strong>No Warranty:</strong> The Website and its content are provided on an "as is" and "as available" basis, without any warranties of any kind, express or implied.</p><p><strong>Use at Your Own Risk:</strong> You use the Website at your own risk. Saras does not warrant that the Website will be error-free, uninterrupted, or secure.</p><p><strong>Limitation of Liability:</strong></p><p><strong>Exclusion of Damages:</strong> In no event shall Saras be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to lost profits, arising out of or in connection with your use of the Website.</p><p><strong>Total Liability:</strong> In no event shall Saras total liability to you for all damages exceed the amount paid by you, if any, for accessing or using the Website.</p><p><strong>Indemnification:</strong></p><p>You agree to indemnify and hold harmless Saras and its officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including reasonable attorneys\' fees, arising out of or in connection with your use of the Website or violation of these Terms.</p><p><strong>Governing Law:</strong></p><p>These Terms shall be governed by and construed in accordance with the laws of Indian govt., without regard to its conflict of law principles.</p><p><strong>Changes to Terms:</strong></p><p>Saras reserves the right to update or modify these Terms at any time without prior notice. Any changes will be effective immediately upon posting on the Website. Your continued use of the Website following the posting of changes constitutes acceptance of such changes.</p><p><strong>Contact Us</strong></p><p>If you have any questions or concerns about these Terms, please contact us at <strong>contact@saras.com</strong></p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2024-05-29 15:16:57',
                'updated_at' => '2024-05-29 15:16:57',
                'scripts' => NULL,
            ],
            [
                'id' => 13,
                'title' => 'Disclaimer',
                'meta_title' => 'Disclaimer',
                'meta_keywords' => 'Disclaimer',
                'meta_description' => 'Disclaimer',
                'short_description' => NULL,
                'description' => '<p>The information provided on <strong>Saras website (the "<strong>www.saras.com</strong>") is for general informational purposes only. While we endeavor to keep the information up to date and accurate, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability with respect to the Website or the information, products, services, or related graphics contained on the Website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</p><p><strong>Professional Advice:</strong></p><p>The information provided on the Website is not intended to constitute professional advice of any kind, including but not limited to legal, financial, or real estate advice. You should consult with qualified professionals in the relevant fields before making any decisions or taking any actions based on the information provided on the Website.</p><p><strong>Property Listings:</strong></p><p>Property listings displayed on the Website are provided by third-party real estate agents or brokers and are for informational purposes only. Saras does not guarantee the accuracy, completeness, or reliability of any property listings or other information provided by third parties on the Website.</p><p><strong>Third-Party Links:</strong></p><p>The Website may contain links to third-party websites or resources. These links are provided solely for your convenience and do not constitute an endorsement, sponsorship, or recommendation by Saras. We have no control over the content or availability of these sites and accept no responsibility for them or for any loss or damage that may arise from your use of them.</p><p><strong>Changes to Information:</strong></p><p>We reserve the right to modify or remove any information on the Website at any time without prior notice. We do not guarantee that the information on the Website will be up-to-date or accurate at all times.</p><p><strong>Limitation of Liability:</strong></p><p>In no event shall Saras be liable for any direct, indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, arising from your use of the Website or reliance on any information provided on the Website.</p><p><strong>Governing Law:</strong></p><p>These disclaimers shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law principles.</p><p><strong>Contact Us:</strong></p><p>If you have any questions or concerns about this disclaimer, please contact us at <strong>contact@saras.com</strong></p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2024-05-29 15:31:20',
                'updated_at' => '2024-05-29 15:31:20',
                'scripts' => NULL,
            ],
            [
                'id' => 14,
                'title' => 'Chairman Message',
                'meta_title' => 'Chairman Message',
                'meta_keywords' => 'Chairman Message',
                'meta_description' => 'Chairman Message',
                'short_description' => '<p style="text-align: center;"><strong>श्री राजेंद्र मोर </strong>(अध्यक्ष)</p>',
                'description' => '<p>श्री गंगानगर जिले से दुग्ध उत्पादकों को बिचैलियों से राहत दिलवाने के लिए राजस्थान काॅपरेटिव डेयरी फैडरेशन लि., जयपुर द्वारा सहकारिता के माध्यम से दुग्ध व्यवसाय को चलाने के लिए माह अप्रैल 1981 से अपनी स्पेयर हैड टीम के माध्यम से श्री गंगानगर जिले में दुग्ध संकलन प्रारम्भ किया गया। दिनांक 30.01.1984 को विधिवत रूप से श्रीगंगानगर जिला दुग्ध उत्पादक सहकारी संघ लि., हनुमानगढ का सहकारिता अधिनियम के अन्तर्गत पंजीयन हुआ। जिसे आज क्षेत्र में &lsquo;&lsquo;गंगमूल डेयरी&rsquo;&rsquo; के नाम से जाना जाता है। गंगमूल दुग्ध उत्पादकों की एक सहकारी संस्था है। जिसका प्रबंधन सहकारिता क्षेत्र से निर्वाचित प्रतिनिधियों के हाथ में होता है। गंगमूल डेयरी का उद्देश्य दुग्ध उत्पादको को उनके दुग्ध की उचित कीमत, उनके दूधारू पशुओं के लिए स्वास्थ सेवाऐं उपलब्ध करवाना व उनका सामाजिक एवं आर्थिक उत्थान करने के साथ साथ शहरी क्षेत्र के दुग्ध उपभोक्ताओं को उचित कीमत पर शुध्द एवं ताजा दूध व दुग्ध उत्पाद उपलब्ध करवाना है।</p><p>&nbsp;</p><p>!!जय सहकार!!</p>',
                'image' => '1760951139.jpg',
                'status' => '1',
                'created_at' => '2025-10-20 03:35:39',
                'updated_at' => '2025-10-20 04:22:26',
                'scripts' => NULL,
            ],
            [
                'id' => 15,
                'title' => 'MD Message',
                'meta_title' => 'MD Message',
                'meta_keywords' => 'MD Message',
                'meta_description' => 'MD Message',
                'short_description' => '<div class="teamnem" style="text-align: center;"><strong>श्री उग्रसेन सहारण </strong>(प्रबन्ध संचालक)</div>',
                'description' => '<p>श्रीगंगानगर जिला दुग्ध उत्पादक सहकारी संघ अपने सदस्यों के आर्थिक, पारिवारिक एंव सामाजिक हिंतो की रक्षा एंव गुणात्मक परिवर्तन के लिये विभिन्न पशु विकास कार्यक्रम, सामाजिक सुरक्षा, डेयरी विकास के माध्यम से उन्हें पूर्ण संतुष्टि देने का प्रयास कर रहा है । संघ द्वारा अपने दुग्ध उत्पादकों को उचित मूल्य पर पशु आहार, मिनरल मिक्सचर, यू0एम0बी0, हरे-चारे के बीज उपलब्ध कराये जाते है इसके साथ साथ पशुपालकों के दूधारू पशुओं हेतु आपातकालीन पशु चिकित्सा, कृत्रिम गर्भाधान, टीकाकरण एंव बांझ निवारण कैम्पों की सुविधा उपलब्ध प्रदान की जा रही है ।</p><p>संघ के सामने प्राइवेट डेयरियों की चुनौति उभर कर सामने आ रही है । इस चुनौति का सफलतापूर्वक मुकाबला संघ द्वारा अपने खर्चो में कटौति कर एंव अपने डेयरी संयत्र की क्षमता का अधिक से अधिक उपयोग कर किया जा रहा है ।</p><p>संघ का मूलभूत सिद्वान्त, जहां एक और ग्रामीण दुग्ध उत्पादको को बिचैलियों से मुक्त कर उनके दूध का अधिकतम मूल्य प्रदान के साथ साथ समस्त पशुपालकों के चहुंमुखी विकास के लिये प्रयत्नशील है । हम निरन्तर बेहतर पशुपालन, स्वच्छ दुग्ध उत्पादन व सामाजिक सुरक्षा के लिये संघ की योजनाओं के माध्यम से पशुपालकों को लाभ पहुंचाने का पूर्ण प्रयास कर रहें है।</p><p>दूध समितियों की कार्यप्रणाली में पारदर्शिता के लिये समितियों का आधुनिकीकरण किया जा रहा है। श्वेत क्रान्ति में महिलाओं की भागीदारी भी सुनिश्चित की जा रही है । स्वच्छ दूध उत्पादन के तहत संघ के विभिन्न दूध मार्गो की समितियों को चरणबद्व तरीके से बल्क मिल्क कूलर स्थापित करने के साथ साथ उन पर आधुनिक तकनीक जैसे ऑटोमेटिक मिल्क कलेक्शन यूनिट, इलेक्ट्रोनिक मिल्कों टेस्टर व लेक्टोस्केन के माध्यम से दूध संकलन की कार्य योजना जारी है ।</p><p>एक ओर जहां संघ के प्रयासों से ग्रामीण क्षेत्र के दुग्ध उत्पादकों को उनके दूध का उचित मूल्य उपलब्ध कराया जा रहा है दूसरी ओर राज्य के शहरी एंव ग्रामीण उपभोक्ताओं की मांग के अनुसार शुद्व, स्वास्थ्यप्रद उत्तम गुणवत्ता के डीटीएम, स्टेण्डर्ड व फुल क्रीम पैकड दूध व दुग्ध पदार्थ घी, टेबल बटर, पनीर, छाछ, लस्सी, फलेवर्ड मिल्क एंव दही की उपलब्धता सुनिश्चित करायी जा कर द्विपक्षीय सामाजिक दायित्वों का निवर्हन संघ द्वारा किया जा रहा है । मैं आशा करता हूं कि आप सभी दुग्ध उत्पादकों, उपभोक्ता एंव अन्य एजेन्सियों का सहयोग सदैव इस संघ को मिलता रहेगा ।</p><p><strong>!!जय सहकार!!</strong></p>',
                'image' => '1760954656.jpg',
                'status' => '1',
                'created_at' => '2025-10-20 04:34:16',
                'updated_at' => '2025-10-20 04:34:16',
                'scripts' => NULL,
            ],
            [
                'id' => 16,
                'title' => 'awards',
                'meta_title' => 'awards',
                'meta_keywords' => 'awards',
                'meta_description' => 'awards',
                'short_description' => '<p>awards</p>',
                'description' => '<p>awards</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-10-20 07:53:22',
                'updated_at' => '2025-10-20 07:53:22',
                'scripts' => NULL,
            ],
            [
                'id' => 17,
                'title' => 'Products',
                'meta_title' => 'Products',
                'meta_keywords' => 'Products',
                'meta_description' => 'Products',
                'short_description' => '<p>Products</p>',
                'description' => '<p>Products</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-20 17:43:09',
                'updated_at' => '2025-11-20 17:43:09',
                'scripts' => 'Products',
            ],
            [
                'id' => 18,
                'title' => 'Tenders',
                'meta_title' => 'Tenders',
                'meta_keywords' => 'Tenders',
                'meta_description' => 'Tenders',
                'short_description' => '<p>Tenders</p>',
                'description' => '<p>Tenders</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-20 18:02:16',
                'updated_at' => '2025-11-20 18:02:16',
                'scripts' => 'Tenders',
            ],
            [
                'id' => 19,
                'title' => 'Milk Purchase Price Charts List',
                'meta_title' => 'Milk Purchase Price Charts List',
                'meta_keywords' => 'Milk Purchase Price Charts List',
                'meta_description' => 'Milk Purchase Price Charts List',
                'short_description' => '<h4 class="mb-sm-0">Milk Purchase Price Charts List</h4><div class="page-title-right">&nbsp;</div>',
                'description' => '<h4 class="mb-sm-0">Milk Purchase Price Charts List</h4><div class="page-title-right">&nbsp;</div>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-22 18:57:19',
                'updated_at' => '2025-11-22 18:57:19',
                'scripts' => 'Milk Purchase Price Charts List',
            ],
            [
                'id' => 20,
                'title' => 'Milk Sale Price Chart',
                'meta_title' => 'Milk Sale Price Chart',
                'meta_keywords' => 'Milk Sale Price Chart',
                'meta_description' => 'Milk Sale Price Chart',
                'short_description' => '<p>Milk Sale Price ChartMilk Sale Price Chart</p>',
                'description' => '<p>Milk Sale Price Chart</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-22 23:03:35',
                'updated_at' => '2025-11-22 23:03:35',
                'scripts' => 'Milk Sale Price Chart',
            ],
            [
                'id' => 21,
                'title' => 'Beneficiaries',
                'meta_title' => 'beneficiaries',
                'meta_keywords' => 'beneficiaries',
                'meta_description' => 'beneficiaries',
                'short_description' => '<p>beneficiaries</p>',
                'description' => '<p>beneficiaries</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-22 23:11:45',
                'updated_at' => '2025-11-22 23:11:45',
                'scripts' => 'beneficiaries',
            ],
            [
                'id' => 22,
                'title' => 'Gallery',
                'meta_title' => 'Gallery',
                'meta_keywords' => 'Gallery',
                'meta_description' => 'Gallery',
                'short_description' => '<p>Gallery</p>',
                'description' => '<p>Gallery</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-23 10:26:59',
                'updated_at' => '2025-11-23 10:26:59',
                'scripts' => 'Gallery',
            ],
            [
                'id' => 23,
                'title' => 'Quality Assurance',
                'meta_title' => 'Quality Assurance',
                'meta_keywords' => 'Quality Assurance',
                'meta_description' => 'Quality Assurance',
                'short_description' => '<p>Quality Assurance</p>',
                'description' => '<p>Quality Assurance</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-23 10:26:59',
                'updated_at' => '2025-11-23 10:26:59',
                'scripts' => 'Quality Assurance',
            ],
            [
                'id' => 24,
                'title' => 'Important Links',
                'meta_title' => 'Important Links',
                'meta_keywords' => 'Important Links',
                'meta_description' => 'Important Links',
                'short_description' => '<p>Important Links</p>',
                'description' => '<p>Important Links</p>',
                'image' => NULL,
                'status' => '1',
                'created_at' => '2025-11-23 10:26:59',
                'updated_at' => '2025-11-23 10:26:59',
                'scripts' => 'Important Links',
            ],
            [
                'id' => 25,
                'title' => 'Important Contacts',
                'meta_title' => 'Important Contacts | Saras',
                'meta_keywords' => 'important contacts, key personnel, saras contacts',
                'meta_description' => 'Find important contacts and key personnel for Saras',
                'short_description' => NULL,
                'description' => NULL,
                'image' => NULL,
                'status' => '0',
                'created_at' => '2025-12-18 18:09:30',
                'updated_at' => '2025-12-18 18:09:30',
                'scripts' => NULL,
            ],
            [
                'id' => 26,
                'title' => 'Our Team',
                'meta_title' => 'Our Team | Saras',
                'meta_keywords' => 'our team, team members, saras team',
                'meta_description' => 'Meet our dedicated team members at Saras',
                'short_description' => NULL,
                'description' => NULL,
                'image' => NULL,
                'status' => '0',
                'created_at' => '2025-12-18 18:45:37',
                'updated_at' => '2025-12-18 18:45:37',
                'scripts' => NULL,
            ],
        ];

        foreach ($pages as $page) {
            DB::table('pages')->updateOrInsert(['id' => $page['id']], $page);
        }
    }
}
